name: "testing, building"
on:
  push:
    branches:
      - main
jobs:
  pipeline:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version:
          - 16.16.x
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.node-version }}"
      - name: install modules
