name: testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
    matrix:
    node-version: [16.x]

  steps:
    -uses: actions/checkout@v2
    -name: Starting Node.js ${{ matrix: node-version}}
     uses: actions/setup-node@v1
     with: 
        node-version: ${{ matrix.node-version }}
    - name: install modules
      run: npm i  
    - name: build production
      run: npm run build
     -name: unit testing
      run: npm run test:unit

